language: cpp
before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
install:
 - sudo apt-get install -qq gcc-4.8 g++-4.8 uuid-dev libprotoc-dev
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
 - wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
 - tar -xzvf protobuf-2.6.1.tar.gz
 - cd protobuf-2.6.1 && ./configure --prefix=/usr && make && make install
script: scons
