language: cpp
before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install libgtest-dev
 - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
install:
 - sudo apt-get install -qq gcc-4.8 g++-4.8 uuid-dev
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
 - wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.bz2
 - tar -xjvf protobuf-2.6.1.tar.bz2
 - cd protobuf-2.6.1 && ./configure --prefix=/usr && make && sudo make install
script: scons
